name: js_wrapping_generator
version: 0.7.4
description: >
  With that package you will be able to easilly generate wrapper for JS library
  in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  collection: ^1.18.0
  js_wrapping: 0.7.5
  source_gen: ^1.5.0
dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers: ^4.0.9
  test:
# dependency_overrides:
#   js_wrapping:
#     path: ../js_wrapping
