name: js_wrapping
version: 0.7.5
description: That package contains elements to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  js: ^0.7.1
